### PR TITLE
ollama: Expose separate completion and chat completion functions

### PR DESCRIPTION
**Pull request by boswelja**
This brings OllamaClient in line with the [API spec](https://github.com/ollama/ollama/blob/main/docs/api.md).

This is also a prerequisite for https://github.com/carlrobertoh/CodeGPT/issues/441

### CODE REVIEW

**Comment by boswelja** [comment]
Apparently I am stupid and missed half the API spec... Please don't merge just yet :laughing:

**Comment by boswelja** [comment]
Current issues are
- Stream unexpectedly closed in local testing
- Tests to be updated

**Comment by boswelja** [comment]
Should be good to go now, I've been playing around with it locally and it's looking OK

**Comment by carlrobertoh** [comment]
Looks good, but it seems that the code style rules are incorrect. Could you import the rules from `config/codestyle.xml` and run the code over with them?
Thank you!

**Comment by boswelja** [comment]
Thanks! Hopefully it's good now.
Mildly related, you should look at defining an `.editorconfig` or something, so the IDE picks up settings without any extra config

**Comment by carlrobertoh** [comment]
Yep, I have thought about that, I just haven't had the time to make it happen yet 😄

**Pull request merged**
